# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection/protos_test/faster_rcnn_resnet101_astronet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from object_detection.protos import model_pb2 as object__detection_dot_protos_dot_model__pb2
from object_detection.protos import train_pb2 as object__detection_dot_protos_dot_train__pb2
from object_detection.protos import eval_pb2 as object__detection_dot_protos_dot_eval__pb2
from object_detection.protos import input_reader_pb2 as object__detection_dot_protos_dot_input__reader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_detection/protos_test/faster_rcnn_resnet101_astronet.proto',
  package='object_detection.protos',
  syntax='proto2',
  serialized_pb=_b('\nAobject_detection/protos_test/faster_rcnn_resnet101_astronet.proto\x12\x17object_detection.protos\x1a#object_detection/protos/model.proto\x1a#object_detection/protos/train.proto\x1a\"object_detection/protos/eval.proto\x1a*object_detection/protos/input_reader.proto\"\xce\x02\n\x1b\x46\x61sterRCNNResnet101AstroNet\x12\x36\n\x05model\x18\x01 \x01(\x0b\x32\'.object_detection.protos.DetectionModel\x12:\n\x0ctrain_config\x18\x02 \x01(\x0b\x32$.object_detection.protos.TrainConfig\x12\x38\n\x0b\x65val_config\x18\x03 \x01(\x0b\x32#.object_detection.protos.EvalConfig\x12@\n\x12train_input_reader\x18\x04 \x01(\x0b\x32$.object_detection.protos.InputReader\x12?\n\x11\x65val_input_reader\x18\x05 \x01(\x0b\x32$.object_detection.protos.InputReader')
  ,
  dependencies=[object__detection_dot_protos_dot_model__pb2.DESCRIPTOR,object__detection_dot_protos_dot_train__pb2.DESCRIPTOR,object__detection_dot_protos_dot_eval__pb2.DESCRIPTOR,object__detection_dot_protos_dot_input__reader__pb2.DESCRIPTOR,])




_FASTERRCNNRESNET101ASTRONET = _descriptor.Descriptor(
  name='FasterRCNNResnet101AstroNet',
  full_name='object_detection.protos.FasterRCNNResnet101AstroNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='object_detection.protos.FasterRCNNResnet101AstroNet.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='object_detection.protos.FasterRCNNResnet101AstroNet.train_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval_config', full_name='object_detection.protos.FasterRCNNResnet101AstroNet.eval_config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_input_reader', full_name='object_detection.protos.FasterRCNNResnet101AstroNet.train_input_reader', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval_input_reader', full_name='object_detection.protos.FasterRCNNResnet101AstroNet.eval_input_reader', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=583,
)

_FASTERRCNNRESNET101ASTRONET.fields_by_name['model'].message_type = object__detection_dot_protos_dot_model__pb2._DETECTIONMODEL
_FASTERRCNNRESNET101ASTRONET.fields_by_name['train_config'].message_type = object__detection_dot_protos_dot_train__pb2._TRAINCONFIG
_FASTERRCNNRESNET101ASTRONET.fields_by_name['eval_config'].message_type = object__detection_dot_protos_dot_eval__pb2._EVALCONFIG
_FASTERRCNNRESNET101ASTRONET.fields_by_name['train_input_reader'].message_type = object__detection_dot_protos_dot_input__reader__pb2._INPUTREADER
_FASTERRCNNRESNET101ASTRONET.fields_by_name['eval_input_reader'].message_type = object__detection_dot_protos_dot_input__reader__pb2._INPUTREADER
DESCRIPTOR.message_types_by_name['FasterRCNNResnet101AstroNet'] = _FASTERRCNNRESNET101ASTRONET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FasterRCNNResnet101AstroNet = _reflection.GeneratedProtocolMessageType('FasterRCNNResnet101AstroNet', (_message.Message,), dict(
  DESCRIPTOR = _FASTERRCNNRESNET101ASTRONET,
  __module__ = 'object_detection.protos_test.faster_rcnn_resnet101_astronet_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.FasterRCNNResnet101AstroNet)
  ))
_sym_db.RegisterMessage(FasterRCNNResnet101AstroNet)


# @@protoc_insertion_point(module_scope)
